"""add preferred_challenges to users and alarms

Revision ID: 379d035e0c77
Revises: 82c0a1dd7572
Create Date: 2026-07-10 03:53:37.152285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '379d035e0c77'
down_revision: Union[str, Sequence[str], None] = '82c0a1dd7572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alarms', sa.Column('preferred_challenges', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('preferred_challenges', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_challenges')
    op.drop_column('alarms', 'preferred_challenges')
    # ### end Alembic commands ###
