"""add analytics and coach

Revision ID: c4338ff126f1
Revises: 379d035e0c77
Create Date: 2026-07-18 17:00:50.611997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4338ff126f1'
down_revision: Union[str, Sequence[str], None] = '379d035e0c77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'wellness_coach'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_bedtime', sa.Time(timezone=True), nullable=True))
    op.add_column('users', sa.Column('target_wake_time', sa.Time(timezone=True), nullable=True))
    op.add_column('users', sa.Column('habit_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'habit_score')
    op.drop_column('users', 'target_wake_time')
    op.drop_column('users', 'target_bedtime')
    # ### end Alembic commands ###
